### ISSUE TITLE
front_landing_page

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/thp_next_kitten_project#1]
**WHY**

Improve UX Design 

**TODO**

* [x] Translate in franch
* [ ] shrink flash message

**MUST HAVE**

* [x] A page in french and beautiful flash message
