### ISSUE TITLE
Refacto_footer

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/thp_next_kitten_project#3]
**WHY**

Improve UX Design 

**TODO**

* [x] Change commercial arguments
* [x] refacto footer template

**MUST HAVE**

* [x] A beautiful footer with strong sell arguments
