### ISSUE TITLE
Refacto_show_cat

### ISSUE THREAD

**Issue by TheMindset** [TheMindset/thp_next_kitten_project#5]
**WHY**

Improve UX Design 

**TODO**

* [x] Resize the pictures
* [x] Design the page

**MUST HAVE**

* [x] A beautiful show cat page
